# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-09 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0002_auto_20170707_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 9, 17, 18, 54, 525963, tzinfo=utc), editable=False),
        ),
    ]
