# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-10 21:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0004_auto_20170710_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 10, 21, 33, 0, 119074, tzinfo=utc), editable=False),
        ),
    ]
