# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0005_auto_20170710_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 6, 49, 11, 987313, tzinfo=utc), editable=False),
        ),
    ]
