# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0006_auto_20170711_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 7, 21, 1, 846027, tzinfo=utc), editable=False),
        ),
    ]
