# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-13 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0008_auto_20170712_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 13, 17, 25, 33, 615883, tzinfo=utc), editable=False),
        ),
    ]
